/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace MultiTokenPaymentChannelFactory {
  export type ChannelStruct = {
    sender: AddressLike;
    recipient: AddressLike;
    token: AddressLike;
    balance: BigNumberish;
    highestNonce: BigNumberish;
    expiration: BigNumberish;
    isClosed: boolean;
  };

  export type ChannelStructOutput = [
    sender: string,
    recipient: string,
    token: string,
    balance: bigint,
    highestNonce: bigint,
    expiration: bigint,
    isClosed: boolean
  ] & {
    sender: string;
    recipient: string;
    token: string;
    balance: bigint;
    highestNonce: bigint;
    expiration: bigint;
    isClosed: boolean;
  };
}

export interface MultiTokenPaymentChannelFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "channels"
      | "closeChannel"
      | "expireChannel"
      | "generateChannelId"
      | "getChannel"
      | "getChannelBalance"
      | "isChannelOpen"
      | "openChannel"
      | "topUpChannel"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ChannelClosed"
      | "ChannelOpened"
      | "ChannelToppedUp"
  ): EventFragment;

  encodeFunctionData(functionFragment: "channels", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "closeChannel",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "expireChannel",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "generateChannelId",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChannel",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getChannelBalance",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isChannelOpen",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openChannel",
    values: [AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "topUpChannel",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "channels", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "closeChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "expireChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "generateChannelId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getChannel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getChannelBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isChannelOpen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openChannel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topUpChannel",
    data: BytesLike
  ): Result;
}

export namespace ChannelClosedEvent {
  export type InputTuple = [
    channelId: BytesLike,
    claimAmount: BigNumberish,
    nonce: BigNumberish
  ];
  export type OutputTuple = [
    channelId: string,
    claimAmount: bigint,
    nonce: bigint
  ];
  export interface OutputObject {
    channelId: string;
    claimAmount: bigint;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChannelOpenedEvent {
  export type InputTuple = [
    channelId: BytesLike,
    sender: AddressLike,
    recipient: AddressLike,
    token: AddressLike,
    balance: BigNumberish,
    expiration: BigNumberish
  ];
  export type OutputTuple = [
    channelId: string,
    sender: string,
    recipient: string,
    token: string,
    balance: bigint,
    expiration: bigint
  ];
  export interface OutputObject {
    channelId: string;
    sender: string;
    recipient: string;
    token: string;
    balance: bigint;
    expiration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ChannelToppedUpEvent {
  export type InputTuple = [
    channelId: BytesLike,
    sender: AddressLike,
    amount: BigNumberish,
    newBalance: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    channelId: string,
    sender: string,
    amount: bigint,
    newBalance: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    channelId: string;
    sender: string;
    amount: bigint;
    newBalance: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MultiTokenPaymentChannelFactory extends BaseContract {
  connect(runner?: ContractRunner | null): MultiTokenPaymentChannelFactory;
  waitForDeployment(): Promise<this>;

  interface: MultiTokenPaymentChannelFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  channels: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        sender: string;
        recipient: string;
        token: string;
        balance: bigint;
        highestNonce: bigint;
        expiration: bigint;
        isClosed: boolean;
      }
    ],
    "view"
  >;

  closeChannel: TypedContractMethod<
    [
      channelId: BytesLike,
      claimAmount: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  expireChannel: TypedContractMethod<
    [channelId: BytesLike],
    [void],
    "nonpayable"
  >;

  generateChannelId: TypedContractMethod<
    [sender: AddressLike, recipient: AddressLike, timestamp: BigNumberish],
    [string],
    "view"
  >;

  getChannel: TypedContractMethod<
    [channelId: BytesLike],
    [MultiTokenPaymentChannelFactory.ChannelStructOutput],
    "view"
  >;

  getChannelBalance: TypedContractMethod<
    [channelId: BytesLike],
    [bigint],
    "view"
  >;

  isChannelOpen: TypedContractMethod<[channelId: BytesLike], [boolean], "view">;

  openChannel: TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      expiration: BigNumberish
    ],
    [string],
    "payable"
  >;

  topUpChannel: TypedContractMethod<
    [channelId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "channels"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        sender: string;
        recipient: string;
        token: string;
        balance: bigint;
        highestNonce: bigint;
        expiration: bigint;
        isClosed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "closeChannel"
  ): TypedContractMethod<
    [
      channelId: BytesLike,
      claimAmount: BigNumberish,
      nonce: BigNumberish,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "expireChannel"
  ): TypedContractMethod<[channelId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "generateChannelId"
  ): TypedContractMethod<
    [sender: AddressLike, recipient: AddressLike, timestamp: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChannel"
  ): TypedContractMethod<
    [channelId: BytesLike],
    [MultiTokenPaymentChannelFactory.ChannelStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getChannelBalance"
  ): TypedContractMethod<[channelId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isChannelOpen"
  ): TypedContractMethod<[channelId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "openChannel"
  ): TypedContractMethod<
    [
      tokenAddress: AddressLike,
      recipient: AddressLike,
      amount: BigNumberish,
      expiration: BigNumberish
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "topUpChannel"
  ): TypedContractMethod<
    [channelId: BytesLike, amount: BigNumberish],
    [void],
    "payable"
  >;

  getEvent(
    key: "ChannelClosed"
  ): TypedContractEvent<
    ChannelClosedEvent.InputTuple,
    ChannelClosedEvent.OutputTuple,
    ChannelClosedEvent.OutputObject
  >;
  getEvent(
    key: "ChannelOpened"
  ): TypedContractEvent<
    ChannelOpenedEvent.InputTuple,
    ChannelOpenedEvent.OutputTuple,
    ChannelOpenedEvent.OutputObject
  >;
  getEvent(
    key: "ChannelToppedUp"
  ): TypedContractEvent<
    ChannelToppedUpEvent.InputTuple,
    ChannelToppedUpEvent.OutputTuple,
    ChannelToppedUpEvent.OutputObject
  >;

  filters: {
    "ChannelClosed(bytes32,uint256,uint256)": TypedContractEvent<
      ChannelClosedEvent.InputTuple,
      ChannelClosedEvent.OutputTuple,
      ChannelClosedEvent.OutputObject
    >;
    ChannelClosed: TypedContractEvent<
      ChannelClosedEvent.InputTuple,
      ChannelClosedEvent.OutputTuple,
      ChannelClosedEvent.OutputObject
    >;

    "ChannelOpened(bytes32,address,address,address,uint256,uint256)": TypedContractEvent<
      ChannelOpenedEvent.InputTuple,
      ChannelOpenedEvent.OutputTuple,
      ChannelOpenedEvent.OutputObject
    >;
    ChannelOpened: TypedContractEvent<
      ChannelOpenedEvent.InputTuple,
      ChannelOpenedEvent.OutputTuple,
      ChannelOpenedEvent.OutputObject
    >;

    "ChannelToppedUp(bytes32,address,uint256,uint256,uint256)": TypedContractEvent<
      ChannelToppedUpEvent.InputTuple,
      ChannelToppedUpEvent.OutputTuple,
      ChannelToppedUpEvent.OutputObject
    >;
    ChannelToppedUp: TypedContractEvent<
      ChannelToppedUpEvent.InputTuple,
      ChannelToppedUpEvent.OutputTuple,
      ChannelToppedUpEvent.OutputObject
    >;
  };
}
