---
version: "2.0"

services:
  nostream:
    image: nostream-ilp:v1.0.0-mainnet
    expose:
      - port: 443
        as: 443
        to:
          - global: true
        proto: tcp
      - port: 8080
        as: 8080
        to:
          - global: true
        proto: tcp
    env:
      - NODE_ENV=production
      - SECRET=${SECRET}
      - RELAY_PORT=8008
      - NOSTR_CONFIG_DIR=/home/node/.nostr
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=nostr_ts_relay
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=nostr_ts_relay
      - DB_MIN_POOL_SIZE=16
      - DB_MAX_POOL_SIZE=64
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BTP_NIPS_ENABLED=true
      - DASSIE_RPC_URL=ws://dassie:7768/trpc
      - DASSIE_RPC_TOKEN=${DASSIE_RPC_TOKEN}
      - DOMAIN=${DOMAIN}
    depends_on:
      - postgres
      - redis
      - dassie

  dassie:
    image: dassie-node:v1.0.0-mainnet
    expose:
      - port: 7768
        to:
          - service: nostream
    env:
      - NODE_ENV=production
      - RPC_AUTH_TOKEN=${DASSIE_RPC_TOKEN}
      - LEDGER_DB_PATH=/app/data/ledger.db
      - SETTLEMENT_BASE_ENABLED=${SETTLEMENT_BASE_ENABLED}
      - SETTLEMENT_BASE_RPC_URL=${SETTLEMENT_BASE_RPC_URL}
      - SETTLEMENT_BASE_FACTORY_ADDRESS=${SETTLEMENT_BASE_FACTORY_ADDRESS}
      - SETTLEMENT_BASE_RELAY_PRIVATE_KEY=${SETTLEMENT_BASE_RELAY_PRIVATE_KEY}
      - SETTLEMENT_CRONOS_ENABLED=${SETTLEMENT_CRONOS_ENABLED}
      - SETTLEMENT_CRONOS_RPC_URL=${SETTLEMENT_CRONOS_RPC_URL}
      - SETTLEMENT_CRONOS_FACTORY_ADDRESS=${SETTLEMENT_CRONOS_FACTORY_ADDRESS}
      - SETTLEMENT_CRONOS_RELAY_PRIVATE_KEY=${SETTLEMENT_CRONOS_RELAY_PRIVATE_KEY}

  postgres:
    image: nostream-postgres:latest
    expose:
      - port: 5432
        to:
          - service: nostream
    env:
      - POSTGRES_DB=nostr_ts_relay
      - POSTGRES_USER=nostr_ts_relay
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  redis:
    image: redis:7-alpine
    expose:
      - port: 6379
        to:
          - service: nostream
    env:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

profiles:
  compute:
    nostream:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 10Gi
    dassie:
      resources:
        cpu:
          units: 0.35
        memory:
          size: 512Mi
        storage:
          size: 5Gi
    postgres:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 512Mi
        storage:
          size: 20Gi
    redis:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 256Mi
        storage:
          size: 1Gi
  placement:
    dcloud:
      pricing:
        nostream:
          denom: uakt
          amount: 550
        dassie:
          denom: uakt
          amount: 200
        postgres:
          denom: uakt
          amount: 300
        redis:
          denom: uakt
          amount: 100

deployment:
  nostream:
    dcloud:
      profile: nostream
      count: 1
  dassie:
    dcloud:
      profile: dassie
      count: 1
  postgres:
    dcloud:
      profile: postgres
      count: 1
  redis:
    dcloud:
      profile: redis
      count: 1
